version: "3.8"
services:
  postgres_milkpay:
    container_name: postgres_milkpay
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1329
    ports:
      - "5447:5432"
  keycloak_milkpay:
    container_name: keycloak_milkpay
    image: jboss/keycloak:12.0.4
    environment: 
        KEYCLOAK_USER: milkPay
        KEYCLOAK_PASSWORD: milkPay
    ports:
      - "9091:8080"    