version: "3.8"
services:
  postgres_milkpay:
    container_name: postgres_milkpay
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1329
    ports:
      - "5447:5432"